# Generated by Django 4.1.6 on 2023-06-12 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(blank=True, max_length=128)),
                ('spain', models.CharField(max_length=128)),
                ('russian', models.CharField(max_length=128)),
                ('lesson', models.PositiveIntegerField(blank=True, default=0)),
                ('learned', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('control', models.BooleanField(default=False)),
                ('phrasal_verbs', models.BooleanField(default=False, verbose_name='exam')),
                ('irregular_verbs', models.BooleanField(default=False)),
                ('info', models.CharField(blank=True, max_length=128)),
                ('repeat_learn', models.IntegerField(default=3)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordParamsSpain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False)),
                ('heavy', models.BooleanField(default=False)),
                ('lesson_1', models.BooleanField(default=False)),
                ('lesson_2', models.BooleanField(default=False)),
                ('lesson_3', models.BooleanField(default=False)),
                ('lesson_4', models.BooleanField(default=False)),
                ('lesson_5', models.BooleanField(default=False)),
                ('lesson_6', models.BooleanField(default=False)),
                ('lesson_7', models.BooleanField(default=False)),
                ('lesson_8', models.BooleanField(default=False)),
                ('lesson_9', models.BooleanField(default=False)),
                ('lesson_10', models.BooleanField(default=False)),
                ('lesson_11', models.BooleanField(default=False)),
                ('lesson_12', models.BooleanField(default=False)),
                ('lesson_13', models.BooleanField(default=False)),
                ('level_1', models.BooleanField(default=False)),
                ('level_2', models.BooleanField(default=False)),
                ('level_3', models.BooleanField(default=False)),
                ('level_4', models.BooleanField(default=False)),
                ('level_5', models.BooleanField(default=False)),
                ('lesson_0', models.BooleanField(default=False)),
                ('irregular_verbs', models.BooleanField(default=False)),
                ('control_state', models.BooleanField(default=False)),
                ('only_important_words', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
